# Github workflow to publish package to NPM and GPR

name: Publish package

on:
  push:

jobs:
  simple:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: rm package-lock.json
      - run: npm i
        env:
          GITHUB_TOKEN: ${{ secrets.READ_PACKAGES_TOKEN }}

  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 10
      - run: npm ci
        env:
          GITHUB_TOKEN: ${{ secrets.READ_PACKAGES_TOKEN }}
      - run: npm run lint
      - run: npm run build

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build

  publish-gpr:
    needs: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          # registry-url: https://npm.pkg.github.com/
          # scope: mojs
      - run: npm ci
        env:
          GITHUB_TOKEN: ${{ secrets.READ_PACKAGES_TOKEN }}
      - run: npm run build
